[tox]
envlist = py310,py311,py312,py313,flake8
requires = tox-uv

[testenv]
dependency_groups = test
commands = pytest --cov=vulcano -k "test_"

[testenv:black]
dependency_groups = lint
commands = black vulcano --line-length=79

[testenv:pylint]
dependency_groups = lint
commands = pylint vulcano

[testenv:flake8]
dependency_groups = lint
commands = flake8 vulcano

[testenv:docs]
dependency_groups = docs
commands =
    sphinx-build -b html -d docs/build/doctrees ./docs/source/ ./docs/build/html
